# Lightning in a Bottle Feature
lightning-in-a-bottle:
  enabled: true
  # Whether the potion should have the enchantment glint
  has-enchantment-glint: false
  # Change the custom model data of the potion item to the number of your resource pack's custom model data predicate
  # Leave null to disable
  custom-model-data: null
  # The behaviour of the lingering bottle of lightning
  # 'VANILLA' casts a lightning bolt to entities that enter the effect cloud
  # 'CONSTANT' casts a single lightning bolt that last the entire duration of the effect cloud
  # 'GM4' casts lightning bolts at random for the duration of the effect cloud
  lingering-lightning-mode: 'VANILLA'

# Blocks or entities tranforming into other entities when hit by lightning
# Entities from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# Blocks from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
lightning-transformations:
  enabled: true
  # From entity to entity
  entities:
    PILLAGER: EVOKER
    EVOKER: ILLUSION
  # From block to entity
  blocks:
    PURPUR_BLOCK: SHULKER
    PRISMARINE_BRICKS: GUARDIAN
    SLIME_BLOCK: SLIME

# Item translations
translations:
  # If your server doesn't have players using different languages, and you wish to disable this feature, you can do so.
  enabled: true
  # For translations, you can use a full locale (e.g. en_US) or just the language (e.g. en).
  # Translations for the normal Bottle of Lightning
  potion-translations:
    en: "Bottle of Lightning"
    es: "Relámpago embotellado"
  # Translations for the Splash Bottle of Lightning
  splash-translations:
    en: "Splash Bottle of Lightning"
    es: "Relámpago embotellado arrojadizo"
  lingering-translations:
    en: "Lingering Bottle of Lightning"
    es: "Relámpago embotellado persistente"
